language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

before_script:
  - flake8 services/

script:
  - pytest --cov-report term --cov="src" -p no:warnings
