version: '3.7'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        entrypoint: ['sh', '/usr/usap/server/app.sh']
        volumes:
            - './services/server:/usr/usap/server'
        ports:
            - 5001:5000
